import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  main: [{type: 'autogenerated', dirName: 'main'}],
  rules: [
    {
      type: 'category',
      label: 'Server Rules',
      link: {
        type: 'doc',
        id: 'rules/server-rules'
      },
      items:
      [
        'rules/cat-a',
        {
          type: 'category',
          label: 'Roleplay Rules',
          link: {
            type: 'doc',
            id: 'rules/cat-b'
          },
          items: ['rules/escalation']
        },
        'rules/cat-c', 'rules/cat-d'
      ]
    },
    {
      type: 'category',
      label: 'Roleplay Guidelines',
      link: {
        type: 'doc',
        id: 'rules/rp-guidelines/rp-guide'
      },
      items:
      [
        'rules/rp-guidelines/rp-players', 'rules/rp-guidelines/rp-game', 'rules/rp-guidelines/rp-emotions'
      ]
    },
    {
      type: 'category',
      label: 'Space Law',
      link: {
        type: 'doc',
        id: 'rules/space-law/space-law'
      },
      items:
      [
        'rules/space-law/crime-list', 'rules/space-law/alert'
      ]
    }
  ],
};

export default sidebars;
